# Generated by Django 5.1 on 2024-08-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('scholarship', models.CharField(choices=[('6eme', '6ème'), ('5eme', '5ème'), ('4eme', '4ème'), ('3eme', '3ème'), ('2nde', '2nde'), ('1ere', '1ère'), ('Tle', 'Terminale')], max_length=5)),
                ('matricula', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
