# Generated by Django 5.1 on 2024-08-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo_name', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=225)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
